name: upload artifacts

on:
  release:
    types: [released]

jobs:
  build-and-upload:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            src: tibasic
            target: ubuntu
          - os: macos-latest
            filename: tibasic
            target: macos
          - os: windows-latest
            filename: tibasic.exe
            target: windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Create build directory
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        run: cmake ${{ github.workspace }} -DCMAKE_BUILD_TYPE=Release

      - name: Build Compiler
        working-directory: ${{runner.workspace}}/build
        run: cmake --build .

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{runner.workspace}}/build/src/${{ matrix.filename }}
          asset_name: ${{ matrix.target }}-${{ matrix.filename }}
