# This workflow will create a GH Releaes whenever a tag is pushed.
# A separate workflow will actually build and upload binaries to the release.

name: create release

on:
  push:
    tags:        
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      id: changelog
      env:
        REPO: ${{ github.repository }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          ${{ steps.changelog.outputs.changelog }}
        # toggle out of draft/pre-release to build artifacts & publish.
        draft: true
        prerelease: true
        generate_release_notes: true
